image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-preview

prebuilds:
  
  - initializeRepos: true

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - ms-python.python

shell:
  init: |
    npm install
